### ISSUE TITLE
Docker way error

### ISSUE THREAD

**Issue by smilesrg** [sobolevbel/jdg#168]
Os X Sonoma 14.3.1 (23D60)
Docker version 20.10.23, build 7155243

docker compose up -d

```
 => ERROR [3/3] RUN pip install -r requirements.txt                                                   21.2s
------
 > [3/3] RUN pip install -r requirements.txt:
#0 4.295 Collecting awesome-slugify==1.6.5 (from -r requirements.txt (line 1))
#0 4.721   Downloading awesome-slugify-1.6.5.tar.gz (8.4 kB)
#0 4.746   Preparing metadata (setup.py): started
#0 5.873   Preparing metadata (setup.py): finished with status 'done'
#0 5.956 Collecting Babel==2.10.3 (from -r requirements.txt (line 2))
#0 6.063   Downloading Babel-2.10.3-py3-none-any.whl.metadata (1.3 kB)
#0 6.351 Collecting certifi==2023.5.7 (from -r requirements.txt (line 3))
#0 6.385   Downloading certifi-2023.5.7-py3-none-any.whl.metadata (2.2 kB)
#0 6.751 Collecting charset-normalizer==2.1.1 (from -r requirements.txt (line 4))
#0 6.789   Downloading charset_normalizer-2.1.1-py3-none-any.whl.metadata (11 kB)
#0 6.904 Collecting click==8.1.3 (from -r requirements.txt (line 5))
#0 6.939   Downloading click-8.1.3-py3-none-any.whl.metadata (3.2 kB)
#0 7.046 Collecting colorama==0.4.6 (from -r requirements.txt (line 6))
#0 7.109   Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
#0 7.274 Collecting ghp-import==2.1.0 (from -r requirements.txt (line 7))
#0 7.319   Downloading ghp_import-2.1.0-py3-none-any.whl.metadata (7.2 kB)
#0 7.411 Collecting gitdb==4.0.9 (from -r requirements.txt (line 8))
#0 7.455   Downloading gitdb-4.0.9-py3-none-any.whl.metadata (998 bytes)
#0 7.579 Collecting GitPython==3.1.31 (from -r requirements.txt (line 9))
#0 7.610   Downloading GitPython-3.1.31-py3-none-any.whl.metadata (1.3 kB)
#0 7.806 Collecting idna==3.4 (from -r requirements.txt (line 10))
#0 7.845   Downloading idna-3.4-py3-none-any.whl.metadata (9.8 kB)
#0 7.968 Collecting Jinja2==3.1.2 (from -r requirements.txt (line 11))
#0 8.001   Downloading Jinja2-3.1.2-py3-none-any.whl.metadata (3.5 kB)
#0 8.235 Collecting Markdown==3.3.7 (from -r requirements.txt (line 12))
#0 8.286   Downloading Markdown-3.3.7-py3-none-any.whl.metadata (4.6 kB)
#0 8.464 Collecting MarkupSafe==2.1.1 (from -r requirements.txt (line 13))
#0 8.497   Downloading MarkupSafe-2.1.1.tar.gz (18 kB)
#0 8.548   Preparing metadata (setup.py): started
#0 8.922   Preparing metadata (setup.py): finished with status 'done'
#0 8.994 Collecting mergedeep==1.3.4 (from -r requirements.txt (line 14))
#0 9.028   Downloading mergedeep-1.3.4-py3-none-any.whl.metadata (4.3 kB)
#0 9.136 Collecting mkdocs==1.5.3 (from -r requirements.txt (line 15))
#0 9.203   Downloading mkdocs-1.5.3-py3-none-any.whl.metadata (6.2 kB)
#0 9.398 Collecting mkdocs-git-revision-date-localized-plugin==1.2.1 (from -r requirements.txt (line 16))
#0 9.436   Downloading mkdocs_git_revision_date_localized_plugin-1.2.1-py3-none-any.whl.metadata (4.8 kB)
#0 9.722 Collecting mkdocs-material==9.4.8 (from -r requirements.txt (line 17))
#0 9.835   Downloading mkdocs_material-9.4.8-py3-none-any.whl.metadata (15 kB)
#0 10.08 Collecting packaging==21.3 (from -r requirements.txt (line 18))
#0 10.12   Downloading packaging-21.3-py3-none-any.whl.metadata (15 kB)
#0 10.28 Collecting paginate==0.5.6 (from -r requirements.txt (line 19))
#0 10.38   Downloading paginate-0.5.6.tar.gz (12 kB)
#0 10.42   Preparing metadata (setup.py): started
#0 10.79   Preparing metadata (setup.py): finished with status 'done'
#0 10.96 Collecting pathspec==0.11.2 (from -r requirements.txt (line 20))
#0 11.00   Downloading pathspec-0.11.2-py3-none-any.whl.metadata (19 kB)
#0 11.12 Collecting platformdirs==4.0.0 (from -r requirements.txt (line 21))
#0 11.16   Downloading platformdirs-4.0.0-py3-none-any.whl.metadata (11 kB)
#0 11.41 Collecting Pygments==2.16.1 (from -r requirements.txt (line 22))
#0 11.44   Downloading Pygments-2.16.1-py3-none-any.whl.metadata (2.5 kB)
#0 11.69 Collecting pymdown-extensions==10.4 (from -r requirements.txt (line 23))
#0 11.73   Downloading pymdown_extensions-10.4-py3-none-any.whl.metadata (3.2 kB)
#0 11.85 Collecting pyparsing==3.0.9 (from -r requirements.txt (line 24))
#0 11.96   Downloading pyparsing-3.0.9-py3-none-any.whl.metadata (4.2 kB)
#0 12.07 Collecting python-dateutil==2.8.2 (from -r requirements.txt (line 25))
#0 12.10   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl.metadata (8.2 kB)
#0 12.30 Collecting pytz==2022.4 (from -r requirements.txt (line 26))
#0 12.35   Downloading pytz-2022.4-py2.py3-none-any.whl.metadata (21 kB)
#0 12.57 Collecting PyYAML==6.0 (from -r requirements.txt (line 27))
#0 12.61   Downloading PyYAML-6.0.tar.gz (124 kB)
#0 12.66      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 2.7 MB/s eta 0:00:00
#0 13.16   Installing build dependencies: started
#0 19.96   Installing build dependencies: finished with status 'done'
#0 19.96   Getting requirements to build wheel: started
#0 20.65   Getting requirements to build wheel: finished with status 'error'
#0 20.68   error: subprocess-exited-with-error
#0 20.68   
#0 20.68   × Getting requirements to build wheel did not run successfully.
#0 20.68   │ exit code: 1
#0 20.68   ╰─> [54 lines of output]
#0 20.68       running egg_info
#0 20.68       writing lib/PyYAML.egg-info/PKG-INFO
#0 20.68       writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
#0 20.68       writing top-level names to lib/PyYAML.egg-info/top_level.txt
#0 20.68       Traceback (most recent call last):
#0 20.68         File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#0 20.68           main()
#0 20.68         File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#0 20.68           json_out['return_val'] = hook(**hook_input['kwargs'])
#0 20.68                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 20.68         File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#0 20.68           return hook(config_settings)
#0 20.68                  ^^^^^^^^^^^^^^^^^^^^^
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
#0 20.68           return self._get_build_requires(config_settings, requirements=['wheel'])
#0 20.68                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
#0 20.68           self.run_setup()
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
#0 20.68           exec(code, locals())
#0 20.68         File "<string>", line 288, in <module>
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
#0 20.68           return distutils.core.setup(**attrs)
#0 20.68                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
#0 20.68           return run_commands(dist)
#0 20.68                  ^^^^^^^^^^^^^^^^^^
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#0 20.68           dist.run_commands()
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
#0 20.68           self.run_command(cmd)
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
#0 20.68           super().run_command(command)
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 20.68           cmd_obj.run()
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run
#0 20.68           self.find_sources()
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
#0 20.68           mm.run()
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run
#0 20.68           self.add_defaults()
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
#0 20.68           sdist.add_defaults(self)
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
#0 20.68           super().add_defaults()
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
#0 20.68           self._add_defaults_ext()
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
#0 20.68           self.filelist.extend(build_ext.get_source_files())
#0 20.68                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 20.68         File "<string>", line 204, in get_source_files
#0 20.68         File "/tmp/pip-build-env-ap_jj2jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
#0 20.68           raise AttributeError(attr)
#0 20.68       AttributeError: cython_sources
#0 20.68       [end of output]
#0 20.68   
#0 20.68   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 20.70 error: subprocess-exited-with-error
#0 20.70 
#0 20.70 × Getting requirements to build wheel did not run successfully.
#0 20.70 │ exit code: 1
#0 20.70 ╰─> See above for output.
#0 20.70 
#0 20.70 note: This error originates from a subprocess, and is likely not a problem with pip.
------
failed to solve: executor failed running [/bin/sh -c pip install -r requirements.txt]: exit code: 1

```

**Comment by iamtodor** [comment]
@smilesrg are you using m-* based architecture?

**Comment by smilesrg** [comment]
@iamtodor Intel Core i7

**Comment by sobolevbel** [comment]
Fixed. Give it a try.

**Comment by pointless-henry** [comment]
@sobolevbel no response from @smilesrg. let's close the ticket?

**Comment by smilesrg** [comment]
@pointless-henry @sobolevbel  Works fine!
